config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :artikels
  get "signup", to: "users#new"
  resources :users, except: [:new]
  #post "users", to: "users#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true 
end

app/models/article.rb
class Article < ApplicationRecord
end 

app/models/artikel.rb
class Artikel < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 2, maximum: 100 }
    validates :description, presence: true, length: { minimum: 2, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :artikels
    validates :username, presence: true, 
                        uniqueness: {case_sensitive: false}, 
                        length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                        uniqueness: {case_sensitive: false}, 
                        length: {maximum: 105},
                        format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # def hello
    #     render html: "Hello World!"
    # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.fetch(:article, {})
    end
end

app/controllers/artikels_controller.rb
class ArtikelsController < ApplicationController

  before_action :set_artikel, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @artikels = Artikel.all
  end

  def new
    @artikel = Artikel.new 
  end

  def create
    @artikel = Artikel.new(artikel_params)
    @artikel.user = User.first
    if @artikel.save
      flash[:notice] = "Artikel was created successfully!"
      redirect_to @artikel
   else
    render "new"
   end
  end

  def edit
  end

  def update
    if @artikel.update(artikel_params)
      flash[:notice] = "Artikel was updated successfully!"
      redirect_to @artikel
    else 
      render "edit"
    end
  end

  def destroy
    @artikel.destroy
    redirect_to artikels_path
  end

  private

  def set_artikel
    @artikel = Artikel.find(params[:id])
  end

  def artikel_params
    params.require(:artikel).permit(:title, :description)
  end
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end 

    def about
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end 

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to artikels_path
        else 
            render "edit"
        end
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice]="Welcome #{@user.username}! You have successfully signed up."
            redirect_to artikels_path
        else
            render "new"   
        end
    end 
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artikels_helper.rb
module ArtikelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit artikel</h1>

<% if @artikel.errors.any?%>
  <h2> The following errors prevented the artikel from being saved </h2>
  <ul>
  <% @artikel.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <%end%>
  </ul>
<%end%>

<%= form_with(model: @artikel, local: true) do |f| %>

  <p>
    <%= f.label :title%> <br/>
    <%= f.text_field :title%>
  </p>

  <p>
    <%= f.label :description%> <br/>
    <%= f.text_area :description%>
  </p>

  <p>
    <%= f.submit%>
  </p>
<%end%>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: black"><%= notice %></p>

<%= render @article %>



<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> 
  <%= link_to "Back to articles", articles_path %>
  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/artikels/_artikel.html.erb
<div id="<%= dom_id artikel %>">
  <p>
    <strong>Title:</strong>
    <%= artikel.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= artikel.description %>
  </p>

</div>

app/views/artikels/_form.html.erb
<%= form_with(model: @artikel, local: true) do |f| %>

<div class="container justify-content-center" id="note">
  <%= render "shared/errors", obj: @artikel %>
  </br>
  <div class="form-group row text-center mt-4 text-black fw-bolder">
    <%= f.label :title, class: "col-2 col-form-label" %> 
    <div class="col-5">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <br>

  <div class="form-group row text-center mt-4 text-black fw-bolder">
    <%= f.label :description, class: "col-2 col-form-label" %> 
    <div class="col-5">
      <%= f.text_area :description, rows: 10, class: "form-control" %>
    </div>
  </div>

  <br>

  <div class="form-group">
    <%= f.submit class: "btn btn-outline-light btn-lg text-black"%> |
    <%= link_to "Back to artikels", artikels_path, class: "btn btn-outline-light btn-lg text-black" %> |
    <%= link_to "Show this artikel", @artikel, class: "btn btn-outline-light btn-lg text-black" %> 
  </div>
  <br>
</div>

<%end%>

app/views/artikels/edit.html.erb
<h1 class="text-center mt-4 fst-italic text-white fw-bolder"> Edit artikel </h1>
<%= render "form" %>

app/views/artikels/index.html.erb
<h1 class="text-center mt-4 fst-italic text-white fw-bolder"> Artikels </h1>
<div class="container">
  <% @artikels.each do |artikel| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center">
          <div class="shadow bg-body rounded">
            <div class="card-header fst-italic" id="note">
              by <%= artikel.user.username%>
            </div>
            <div class="card-body" index="_body" id="note">
            <h5 class="card-title"> <%= link_to artikel.title, artikel_path(artikel), class: "text-success"%>  </h5>
              <p class="card-text" > <%= truncate(artikel.description, length: 20) %> </p>
                <button type="button" class="btn btn-outline-danger"> <%= link_to "Delete", artikel_path(artikel), method: :delete, data: { confirm: "Are you sure?"}, class: "text-danger" %> </button>
                <button type="button" class="btn btn-outline-primary"> <%= link_to "Show", artikel_path(artikel), class: "text-primary" %></button> 
                <button type="button" class="btn btn-outline-success"> <%= link_to "Edit", edit_artikel_path(artikel), class: "text-success" %></button> 
            </div>
            <div class="card-footer text-black" id="note">
              <small> Created <%= time_ago_in_words(artikel.created_at) %> ago |
                      Edited <%= time_ago_in_words(artikel.updated_at) %> ago </small>
            </div>
          </div>
        </div>
        </br>
      </div>
    </div>
  <%end%>
</div>

app/views/artikels/new.html.erb
<h1 class="text-center mt-4 fst-italic text-white fw-bolder"> Create new artikel </h1>
<%= render "form" %>

app/views/artikels/show.html.erb
<h1 class="text-center mt-4 fst-italic text-white fw-bolder"> Showing Artikels </h1>
<div class="container justify-content-center">
  <div class="col-8 mt-4">
    <div class="card text-center">
      <div class="shadow bg-body rounded">
        <div class="card-header fst-italic" id="note">
          by <%= @artikel.user.username if @artikel.user%>
        </div>
        <div class="card-body" index="_body" id="note">
          <h5 class="card-title"> <%= @artikel.title %>   </h5>
            <p class="card-text" > <%= @artikel.description %>  </p>
              <%= button_to "Delete", artikel_path(@artikel), method: :delete, class: "text-danger" %>
            <button type="button" class="btn btn-outline-primary"> <%= link_to "Show", artikel_path(@artikel), class: "text-primary" %></button> 
            <button type="button" class="btn btn-outline-success"> <%= link_to "Edit", edit_artikel_path(@artikel), class: "text-success" %></button> 
        </div>
        <div class="card-footer text-black" id="note">
        <small> Created <%= time_ago_in_words(@artikel.created_at) %> ago |
                Edited <%= time_ago_in_words(@artikel.updated_at) %> ago </small>
        </div>
      </div>
    </div>
    </br>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer" class="d-flex flex-wrap justify-content-between align-items-center">
    <p class="col-md-4 mb-0 text-muted">&copy; <%= link_to "Aedify", "https://aedify.de/" %></p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"> <%= link_to "About", about_path %> </li>
    </ul>
</footer>

app/views/layouts/_messages.html.erb
<div class="containter">
      <% flash.each do |name, msg| %>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <%= msg %>
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
      <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg " id="navbar">
  <div class="container-fluid">
    <%= link_to "KiBi", root_path, class: "navbar-brand", id: "logo" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Artikels
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li> <a class="dropdown-item" <%= link_to "Artikels listing", artikels_path, class: "nav-link"%> </a> </li>
            <li> <a class="dropdown-item" <%= link_to "Create new artikel", new_artikel_path, class: "nav-link" %> </a> </li> 
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <div id="page-content">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>

</html>

app/views/pages/about.html.erb
<h1> This is the About Page</h1>

app/views/pages/home.html.erb
<div class="container" id ="home-container">
    <div class="jumbotron text-center text-black">
    <br><br><br><br><br>
        <h5 class="card-title">Welcome to our website</h5>
        <p class="card-text">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-success" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
</br>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong> The following errors prevented the <%= obj.class.name.downcase %> from being saved </strong>  
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
    </ul>
</div>
<%end%>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
<div class="container justify-content-center" id="note">
    <%= render "shared/errors", obj: @user %>
    </br>
    <div class="form-group row text-center mt-4 text-black fw-bolder">
        <%= f.label :username, class: "col-2 col-form-label" %> 
        <div class="col-5">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter a username." %>
        </div>
    </div>
    <br>    
    <div class="form-group row text-center mt-4 text-black fw-bolder">
        <%= f.label :email, class: "col-2 col-form-label" %> 
        <div class="col-5">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter your email adress."  %>
        </div>
    </div>

    <div class="form-group row text-center mt-4 text-black fw-bolder">
        <%= f.label :password, class: "col-2 col-form-label" %> 
        <div class="col-5">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter your password."  %>
        </div>
    </div>
    <br>
    <div class="form-group">
        <%= f.submit(@user.new_record? ? "Sign up": "Update account", class: "btn btn-outline-light btn-lg text-black") %> |
        <%= link_to "Back to artikels", artikels_path, class: "btn btn-outline-light btn-lg text-black" %> 
    </div>
    <br>
</div>
<%end%>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 fst-italic text-white fw-bolder"> Edit your profile </h1>
<%= render "form" %>

app/views/users/new.html.erb
<h1 class="text-center mt-4 fst-italic text-white fw-bolder"> Sign up </h1>
<%= render "form" %>